 /******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Muhamed Amr
 ******************************************************************************/

#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between PORT_PBcfg.c and PORT.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between PORT_PBcfg.c and PORT.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif

/* PB structure used with PORT_Init API */
const Port_ConfigType PORT_Configuration =

                    {
                     PORT_PORTA,PORT_PIN0,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTA,PORT_PIN1,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTA,PORT_PIN2,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTA,PORT_PIN3,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTA,PORT_PIN4,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTA,PORT_PIN5,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTA,PORT_PIN6,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTA,PORT_PIN7,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,


                     PORT_PORTB,PORT_PIN0,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTB,PORT_PIN1,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTB,PORT_PIN2,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTB,PORT_PIN3,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTB,PORT_PIN4,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTB,PORT_PIN5,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTB,PORT_PIN6,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTB,PORT_PIN7,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,


                     PORT_PORTC,PORT_PIN4,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTC,PORT_PIN5,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTC,PORT_PIN6,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTC,PORT_PIN7,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,


                     PORT_PORTD,PORT_PIN0,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTD,PORT_PIN1,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTD,PORT_PIN2,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTD,PORT_PIN3,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTD,PORT_PIN4,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTD,PORT_PIN5,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTD,PORT_PIN6,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_UNCHANGEABLE,
                     PORT_PORTD,PORT_PIN7,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_UNCHANGEABLE,


                     PORT_PORTE,PORT_PIN0,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTE,PORT_PIN1,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTE,PORT_PIN2,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTE,PORT_PIN3,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTE,PORT_PIN4,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTE,PORT_PIN5,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,


                     PORT_PORTF,PORT_PIN0,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PortConf_SW1_PORT_NUM,PortConf_LED1_PIN_NUM,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE, /* LED1 */
                     PORT_PORTF,PORT_PIN2,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PORT_PORTF,PORT_PIN3,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE,
                     PortConf_SW1_PORT_NUM,PortConf_SW1_PIN_NUM,PORT_PIN_IN,PORT_PIN_MODE_DIO,OFF,PORT_PIN_LEVEL_HIGH,PORT_PIN_CHANGEABLE,PORT_PIN_CHANGEABLE
                    };
